In [1]:
%%capture output
!pip install anndata
!pip install scanpy

In [2]:
import pickle
import anndata as ad
import scanpy as sc
import numpy as np
import os
import pandas as pd

/dss/dsshome1/02/di93zoj/.local/lib/python3.8/site-packages/cupy/_environment.py:445: UserWarning:
--------------------------------------------------------------------------------

  CuPy may not function correctly because multiple CuPy packages are installed
  in your environment:

    cupy-cuda11x, cupy-cuda12x

  Follow these steps to resolve this issue:

    1. For all packages listed above, run the following command to remove all
       existing CuPy installations:

         $ pip uninstall <package_name>

      If you previously installed CuPy via conda, also run the following:

         $ conda uninstall cupy

    2. Install the appropriate CuPy package.
       Refer to the Installation Guide for detailed instructions.

         https://docs.cupy.dev/en/stable/install.html

--------------------------------------------------------------------------------

  warnings.warn(f'''

In [3]:
metadata = pickle.load(open('/dss/dssfs02/lwp-dss-0001/pn36po/pn36po-dss-0001/di93zoj/kaggle/full_data/20220830_citeseq_metadata_cells.pkl', 'rb'))
metadata[metadata['kaggle_dataset'] == 'test_private']

                                kaggle_dataset  day  donor cell_type
CATAAGCAGCATGATA-1-('27678', 7)   test_private    7  27678      MasP
GGTGATTGTATGAAAC-1-('27678', 7)   test_private    7  27678       HSC
ATAGGCTAGCTCTGTA-1-('27678', 7)   test_private    7  27678      MasP
TCATGAGGTGGATTTC-1-('27678', 7)   test_private    7  27678      MasP
TAAGCGTTCGGCTGGT-1-('27678', 7)   test_private    7  27678       HSC
...                                        ...  ...    ...       ...
AGGTTGTAGTGCAGCA-1-('31800', 7)   test_private    7  31800       HSC
CGTCAAATCCTCTGCA-1-('31800', 7)   test_private    7  31800       HSC
ACTCCCATCCATAGGT-1-('31800', 7)   test_private    7  31800       MkP
GTGGCGTCATACTGAC-1-('31800', 7)   test_private    7  31800      EryP
TACTTGTCAACAAGTA-1-('31800', 7)   test_private    7  31800      EryP

[26867 rows x 4 columns]

In [4]:
pickle.load(open('/dss/dssfs02/lwp-dss-0001/pn36po/pn36po-dss-0001/di93zoj/kaggle/full_data/20220830_citeseq_rna_count_train.pkl', 'rb'))

gene_ids,ENSG00000121410_A1BG,ENSG00000268895_A1BG-AS1,ENSG00000175899_A2M,ENSG00000245105_A2M-AS1,ENSG00000166535_A2ML1,ENSG00000128274_A4GALT,ENSG00000094914_AAAS,ENSG00000081760_AACS,ENSG00000109576_AADAT,ENSG00000103591_AAGAB,...,ENSG00000153975_ZUP1,ENSG00000086827_ZW10,ENSG00000174442_ZWILCH,ENSG00000122952_ZWINT,ENSG00000198205_ZXDA,ENSG00000198455_ZXDB,ENSG00000070476_ZXDC,ENSG00000162378_ZYG11B,ENSG00000159840_ZYX,ENSG00000074755_ZZEF1
"GTAGGAGCAGCGGTTC-1-('32606', 2)",0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.000000,4.090185,0.000000
"GAGATGGGTAATGATG-1-('32606', 2)",0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,4.039545,0.0,0.0,0.000000,0.000000,0.000000,0.000000
"AGGATCTGTATTTCGG-1-('32606', 2)",0.0,0.0,0.0,0.0,0.0,3.847321,0.000000,3.847321,3.847321,0.000000,...,0.000000,0.000000,3.847321,4.529743,0.0,0.0,0.000000,3.847321,3.847321,0.000000
"CAAAGAATCCAAAGGG-1-('32606', 2)",0.0,0.0,0.0,0.0,0.0,0.000000,3.436846,3.436846,0.000000,0.000000,...,3.436846,0.000000,4.113780,5.020215,0.0,0.0,0.000000,3.436846,4.113780,0.000000
"AGCCACGTCCCAATAG-1-('32606', 2)",0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,4.196826,0.000000,0.000000,...,0.000000,4.196826,4.196826,4.196826,0.0,0.0,3.518610,4.196826,3.518610,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
"TGTTCCGTCAGCGTCG-1-('31800', 4)",0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,4.397535,4.397535,5.084510,0.0,0.0,0.000000,0.000000,4.397535,4.397535
"TTTAGTCTCCATAGAC-1-('31800', 4)",0.0,0.0,0.0,0.0,0.0,0.000000,3.981467,4.665241,0.000000,0.000000,...,3.981467,0.000000,4.665241,3.981467,0.0,0.0,0.000000,0.000000,3.981467,0.000000
"AGATGCTCAGCGCGTT-1-('31800', 4)",0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,4.497696,0.000000,4.497696,...,0.000000,0.000000,0.000000,4.497696,0.0,0.0,3.815622,4.497696,0.000000,0.000000
"ATCACGACACATATGC-1-('31800', 4)",0.0,0.0,0.0,0.0,0.0,0.000000,3.900907,0.000000,0.000000,4.583891,...,0.000000,0.000000,4.583891,4.985945,0.0,0.0,0.000000,0.000000,0.000000,3.900907
"GGTGAAGAGAGAGGGC-1-('31800', 4)",0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,...,4.189502,0.000000,0.000000,4.189502,0.0,0.0,0.000000,0.000000,4.189502,4.189502

In [5]:
private_test_input = pickle.load(open('/dss/dssfs02/lwp-dss-0001/pn36po/pn36po-dss-0001/di93zoj/kaggle/full_data/20220830_citeseq_rna_count_test_input_private.pkl', 'rb'))
private_test_input

gene_ids,ENSG00000121410_A1BG,ENSG00000268895_A1BG-AS1,ENSG00000175899_A2M,ENSG00000245105_A2M-AS1,ENSG00000166535_A2ML1,ENSG00000128274_A4GALT,ENSG00000094914_AAAS,ENSG00000081760_AACS,ENSG00000109576_AADAT,ENSG00000103591_AAGAB,...,ENSG00000153975_ZUP1,ENSG00000086827_ZW10,ENSG00000174442_ZWILCH,ENSG00000122952_ZWINT,ENSG00000198205_ZXDA,ENSG00000198455_ZXDB,ENSG00000070476_ZXDC,ENSG00000162378_ZYG11B,ENSG00000159840_ZYX,ENSG00000074755_ZZEF1
"CATAAGCAGCATGATA-1-('27678', 7)",0.000000,0.000000,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,4.749682,...,0.000000,0.000000,0.000000,5.438493,0.000000,0.0,0.000000,0.000000,4.065152,0.000000
"GGTGATTGTATGAAAC-1-('27678', 7)",0.000000,3.834347,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,3.834347,...,0.000000,0.000000,3.834347,3.834347,0.000000,0.0,3.834347,0.000000,5.204297,0.000000
"ATAGGCTAGCTCTGTA-1-('27678', 7)",0.000000,0.000000,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,5.248719
"TCATGAGGTGGATTTC-1-('27678', 7)",0.000000,0.000000,0.0,0.0,0.0,0.0,4.455667,4.455667,0.000000,4.455667,...,4.455667,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,5.142992,0.000000
"TAAGCGTTCGGCTGGT-1-('27678', 7)",3.560507,0.000000,0.0,0.0,0.0,0.0,0.000000,4.639987,0.000000,0.000000,...,3.560507,0.000000,3.560507,4.925252,0.000000,0.0,0.000000,0.000000,0.000000,4.239340
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
"AGGTTGTAGTGCAGCA-1-('31800', 7)",0.000000,0.000000,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,3.719836,...,0.000000,0.000000,0.000000,3.719836,0.000000,0.0,0.000000,0.000000,3.719836,0.000000
"CGTCAAATCCTCTGCA-1-('31800', 7)",0.000000,0.000000,0.0,0.0,0.0,0.0,0.000000,0.000000,4.026206,0.000000,...,4.026206,0.000000,0.000000,4.026206,0.000000,0.0,0.000000,0.000000,4.710393,0.000000
"ACTCCCATCCATAGGT-1-('31800', 7)",0.000000,0.000000,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,4.306634,0.000000,0.000000,0.0,0.000000,4.306634,6.933096,4.993019
"GTGGCGTCATACTGAC-1-('31800', 7)",0.000000,0.000000,0.0,0.0,0.0,0.0,3.624848,3.624848,0.000000,0.000000,...,0.000000,0.000000,0.000000,3.624848,3.624848,0.0,0.000000,3.624848,0.000000,0.000000
"TACTTGTCAACAAGTA-1-('31800', 7)",0.000000,0.000000,0.0,0.0,0.0,0.0,0.000000,4.452700,0.000000,3.377115,...,3.377115,3.377115,0.000000,4.737466,0.000000,0.0,0.000000,0.000000,0.000000,0.000000

In [6]:
private_test_input_raw = pickle.load(open('/dss/dssfs02/lwp-dss-0001/pn36po/pn36po-dss-0001/di93zoj/kaggle/full_data/20220830_citeseq_rna_count_test_input_private_raw.pkl', 'rb'))
private_test_input_raw

gene_ids,ENSG00000121410_A1BG,ENSG00000268895_A1BG-AS1,ENSG00000175899_A2M,ENSG00000245105_A2M-AS1,ENSG00000166535_A2ML1,ENSG00000128274_A4GALT,ENSG00000094914_AAAS,ENSG00000081760_AACS,ENSG00000109576_AADAT,ENSG00000103591_AAGAB,...,ENSG00000153975_ZUP1,ENSG00000086827_ZW10,ENSG00000174442_ZWILCH,ENSG00000122952_ZWINT,ENSG00000198205_ZXDA,ENSG00000198455_ZXDB,ENSG00000070476_ZXDC,ENSG00000162378_ZYG11B,ENSG00000159840_ZYX,ENSG00000074755_ZZEF1
"CATAAGCAGCATGATA-1-('27678', 7)",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,...,0.0,0.0,0.0,4.0,0.0,0.0,0.0,0.0,1.0,0.0
"GGTGATTGTATGAAAC-1-('27678', 7)",0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0,4.0,0.0
"ATAGGCTAGCTCTGTA-1-('27678', 7)",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
"TCATGAGGTGGATTTC-1-('27678', 7)",0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0
"TAAGCGTTCGGCTGGT-1-('27678', 7)",1.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0,0.0,0.0,...,1.0,0.0,1.0,4.0,0.0,0.0,0.0,0.0,0.0,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
"AGGTTGTAGTGCAGCA-1-('31800', 7)",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
"CGTCAAATCCTCTGCA-1-('31800', 7)",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,2.0,0.0
"ACTCCCATCCATAGGT-1-('31800', 7)",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,14.0,2.0
"GTGGCGTCATACTGAC-1-('31800', 7)",0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,...,0.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0
"TACTTGTCAACAAGTA-1-('31800', 7)",0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0,0.0,1.0,...,1.0,1.0,0.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0

In [7]:
private_test_target = pickle.load(open('/dss/dssfs02/lwp-dss-0001/pn36po/pn36po-dss-0001/di93zoj/kaggle/full_data/20220830_citeseq_prot_count_test_labels_private.pkl', 'rb'))
private_test_target

gene_ids,CD86,CD274,CD270,CD155,CD112,CD47,CD48,CD40,CD154,CD52,...,CD94,CD162,CD85j,CD23,CD328,HLA-E,CD82,CD101,CD88,CD224
"CATAAGCAGCATGATA-1-('27678', 7)",8.875269,1.072714,0.349734,2.983766,3.551555,10.595364,17.327169,-0.144145,1.184181,3.041042,...,0.191373,11.086969,0.300469,0.805080,-0.291616,1.635413,7.509739,6.417010,-0.497571,3.759374
"GGTGATTGTATGAAAC-1-('27678', 7)",-0.331542,0.871559,0.484194,-0.784014,4.173365,5.242312,3.511576,1.208851,0.547345,-1.133742,...,0.310369,7.197814,-0.425260,-0.154081,-0.124246,-0.106671,3.812726,-0.155547,1.029169,3.598739
"ATAGGCTAGCTCTGTA-1-('27678', 7)",-0.211242,0.736260,1.096481,1.892444,1.585475,3.669683,2.232614,-1.042255,0.724554,0.833527,...,-0.204551,8.529263,1.732819,0.772459,-0.043307,0.747416,1.233450,0.753507,0.735868,1.859444
"TCATGAGGTGGATTTC-1-('27678', 7)",4.110175,1.230138,0.494763,2.138238,4.675085,7.903718,12.580855,1.051892,2.035204,-0.039051,...,-0.094660,6.203796,1.358820,0.798049,-0.224005,0.375061,6.693098,2.614395,0.998246,3.432812
"TAAGCGTTCGGCTGGT-1-('27678', 7)",0.259446,0.755755,1.337115,0.549588,1.717137,3.052538,3.472257,0.744798,0.519145,0.829422,...,-0.103484,1.742605,0.397716,-0.141199,0.273376,1.399987,1.973929,-0.221435,1.301512,4.906563
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
"AGGTTGTAGTGCAGCA-1-('31800', 7)",-0.248526,1.108229,-0.532460,5.203330,4.384092,4.525804,9.671577,-1.028414,-0.151672,-0.854226,...,0.262863,2.934531,0.420953,-0.518197,-0.096301,0.631488,0.816986,-0.666768,0.601364,0.211863
"CGTCAAATCCTCTGCA-1-('31800', 7)",2.636508,-0.333341,1.703799,1.690464,4.803713,2.959094,6.515352,0.565887,-0.028127,1.338429,...,1.437733,4.493226,0.752311,0.534301,0.058650,1.605893,2.946751,0.553264,0.430055,3.014829
"ACTCCCATCCATAGGT-1-('31800', 7)",-0.684045,1.742048,0.944750,2.119234,6.383219,15.623772,3.996019,8.893702,-0.564551,-0.675288,...,-1.677220,3.575482,0.858454,-1.053894,-0.374440,1.007881,3.143887,-0.023827,0.074430,5.129007
"GTGGCGTCATACTGAC-1-('31800', 7)",0.801277,-0.431385,0.650719,3.207137,-0.080855,5.052996,-0.557722,0.609040,1.801432,0.661264,...,0.689368,3.605958,1.000461,0.202446,-0.308034,0.846841,6.123100,0.823352,7.600136,3.632790
"TACTTGTCAACAAGTA-1-('31800', 7)",-0.377480,0.903240,1.169246,4.286571,2.107780,2.658981,-0.547910,0.207357,0.460619,1.940052,...,-0.677536,6.298780,1.739152,0.303523,-0.178656,0.461010,8.226444,0.412474,7.434890,3.387622

In [8]:
private_test_target_raw = pickle.load(open('/dss/dssfs02/lwp-dss-0001/pn36po/pn36po-dss-0001/di93zoj/kaggle/full_data/20220830_citeseq_prot_count_test_labels_private_raw.pkl', 'rb'))
private_test_target_raw

gene_ids,CD86,CD274,CD270,CD155,CD112,CD47,CD48,CD40,CD154,CD52,...,CD94,CD162,CD85j,CD23,CD328,HLA-E,CD82,CD101,CD88,CD224
"CATAAGCAGCATGATA-1-('27678', 7)",10.0,8.0,11.0,7.0,30.0,15.0,21.0,2.0,23.0,9.0,...,13.0,22.0,3.0,36.0,0.0,11.0,48.0,39.0,5.0,17.0
"GGTGATTGTATGAAAC-1-('27678', 7)",0.0,6.0,10.0,0.0,34.0,6.0,3.0,4.0,16.0,0.0,...,12.0,12.0,1.0,22.0,0.0,4.0,18.0,3.0,9.0,15.0
"ATAGGCTAGCTCTGTA-1-('27678', 7)",0.0,5.0,12.0,4.0,15.0,4.0,2.0,0.0,16.0,3.0,...,9.0,15.0,5.0,29.0,0.0,6.0,7.0,5.0,7.0,8.0
"TCATGAGGTGGATTTC-1-('27678', 7)",4.0,8.0,11.0,5.0,40.0,10.0,13.0,4.0,29.0,2.0,...,11.0,10.0,5.0,34.0,0.0,6.0,39.0,13.0,10.0,15.0
"TAAGCGTTCGGCTGGT-1-('27678', 7)",0.0,3.0,10.0,1.0,14.0,3.0,3.0,2.0,11.0,2.0,...,7.0,3.0,1.0,15.0,0.0,6.0,8.0,1.0,6.0,18.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
"AGGTTGTAGTGCAGCA-1-('31800', 7)",0.0,6.0,4.0,11.0,31.0,5.0,8.0,0.0,9.0,0.0,...,9.0,4.0,2.0,14.0,0.0,5.0,5.0,1.0,6.0,3.0
"CGTCAAATCCTCTGCA-1-('31800', 7)",2.0,1.0,11.0,3.0,33.0,3.0,5.0,2.0,8.0,3.0,...,13.0,6.0,2.0,19.0,0.0,7.0,11.0,3.0,4.0,10.0
"ACTCCCATCCATAGGT-1-('31800', 7)",0.0,11.0,12.0,5.0,57.0,28.0,3.0,30.0,10.0,1.0,...,4.0,5.0,4.0,15.0,0.0,8.0,15.0,4.0,7.0,23.0
"GTGGCGTCATACTGAC-1-('31800', 7)",1.0,3.0,10.0,7.0,7.0,6.0,0.0,3.0,24.0,3.0,...,13.0,5.0,4.0,24.0,0.0,7.0,32.0,6.0,72.0,15.0
"TACTTGTCAACAAGTA-1-('31800', 7)",0.0,6.0,11.0,9.0,16.0,3.0,0.0,2.0,13.0,5.0,...,6.0,9.0,5.0,22.0,0.0,5.0,49.0,4.0,63.0,13.0

In [9]:
metadata_filtered = metadata[metadata.index.isin(private_test_input.index)]
metadata_filtered

                                kaggle_dataset  day  donor cell_type
CATAAGCAGCATGATA-1-('27678', 7)   test_private    7  27678      MasP
GGTGATTGTATGAAAC-1-('27678', 7)   test_private    7  27678       HSC
ATAGGCTAGCTCTGTA-1-('27678', 7)   test_private    7  27678      MasP
TCATGAGGTGGATTTC-1-('27678', 7)   test_private    7  27678      MasP
TAAGCGTTCGGCTGGT-1-('27678', 7)   test_private    7  27678       HSC
...                                        ...  ...    ...       ...
AGGTTGTAGTGCAGCA-1-('31800', 7)   test_private    7  31800       HSC
CGTCAAATCCTCTGCA-1-('31800', 7)   test_private    7  31800       HSC
ACTCCCATCCATAGGT-1-('31800', 7)   test_private    7  31800       MkP
GTGGCGTCATACTGAC-1-('31800', 7)   test_private    7  31800      EryP
TACTTGTCAACAAGTA-1-('31800', 7)   test_private    7  31800      EryP

[26867 rows x 4 columns]

In [10]:
private_test_input = ad.AnnData(private_test_input, obs=metadata_filtered)
private_test_target = ad.AnnData(private_test_target, obs=metadata_filtered)
private_test_input_raw = ad.AnnData(private_test_input_raw, obs=metadata_filtered)
private_test_target_raw = ad.AnnData(private_test_target_raw, obs=metadata_filtered)
private_test_input

AnnData object with n_obs Ã— n_vars = 26867 Ã— 22085
    obs: 'kaggle_dataset', 'day', 'donor', 'cell_type'

In [11]:
private_test_target

AnnData object with n_obs Ã— n_vars = 26867 Ã— 140
    obs: 'kaggle_dataset', 'day', 'donor', 'cell_type'

In [12]:
private_test_target.obs.index.tolist()[:10]

["CATAAGCAGCATGATA-1-('27678', 7)",
 "GGTGATTGTATGAAAC-1-('27678', 7)",
 "ATAGGCTAGCTCTGTA-1-('27678', 7)",
 "TCATGAGGTGGATTTC-1-('27678', 7)",
 "TAAGCGTTCGGCTGGT-1-('27678', 7)",
 "GGGAGTAAGAAGCTGC-1-('27678', 7)",
 "CACTAAGAGCAGCAGT-1-('27678', 7)",
 "TGCGATATCCTCTAAT-1-('27678', 7)",
 "CATACAGTCTCATGCC-1-('27678', 7)",
 "TGTAGACGTTTACTTC-1-('27678', 7)"]

In [13]:
private_test_target.var.index.tolist()[:10]

['CD86',
 'CD274',
 'CD270',
 'CD155',
 'CD112',
 'CD47',
 'CD48',
 'CD40',
 'CD154',
 'CD52']

In [14]:
private_test_input.write("/dss/dssfs02/lwp-dss-0001/pn36po/pn36po-dss-0001/di93zoj/large_preprocessed_files/private_test_input.h5ad")
private_test_target.write("/dss/dssfs02/lwp-dss-0001/pn36po/pn36po-dss-0001/di93zoj/large_preprocessed_files/private_test_target.h5ad")

In [15]:
private_test_input_raw.write("/dss/dssfs02/lwp-dss-0001/pn36po/pn36po-dss-0001/di93zoj/large_preprocessed_files/private_test_input_raw.h5ad")
private_test_target_raw.write("/dss/dssfs02/lwp-dss-0001/pn36po/pn36po-dss-0001/di93zoj/large_preprocessed_files/private_test_target_raw.h5ad")

### preprocess input data - make-base-feature

In [16]:
private_test_input.X

<26867x22085 sparse matrix of type '<class 'numpy.float32'>'
	with 127598600 stored elements in Compressed Sparse Row format>

In [17]:
important_cols = ['ENSG00000135218_CD36',
 'ENSG00000010278_CD9',
 'ENSG00000204287_HLA-DRA',
 'ENSG00000117091_CD48',
 'ENSG00000004468_CD38',
 'ENSG00000173762_CD7',
 'ENSG00000137101_CD72',
 'ENSG00000019582_CD74',
 'ENSG00000169442_CD52',
 'ENSG00000170458_CD14',
 'ENSG00000272398_CD24',
 'ENSG00000026508_CD44',
 'ENSG00000114013_CD86',
 'ENSG00000174059_CD34',
 'ENSG00000139193_CD27',
 'ENSG00000105383_CD33',
 'ENSG00000085117_CD82',
 'ENSG00000177455_CD19',
 'ENSG00000002586_CD99',
 'ENSG00000196126_HLA-DRB1',
 'ENSG00000135404_CD63',
 'ENSG00000012124_CD22',
 'ENSG00000134061_CD180',
 'ENSG00000105369_CD79A',
 'ENSG00000116824_CD2',
 'ENSG00000010610_CD4',
 'ENSG00000139187_KLRG1',
 'ENSG00000204592_HLA-E',
 'ENSG00000090470_PDCD7',
 'ENSG00000206531_CD200R1L',
'ENSG00000166710_B2M',
 'ENSG00000198034_RPS4X',
 'ENSG00000188404_SELL',
 'ENSG00000130303_BST2',
 'ENSG00000128040_SPINK2',
 'ENSG00000206503_HLA-A',
 'ENSG00000108107_RPL28',
 'ENSG00000143226_FCGR2A',
 'ENSG00000133112_TPT1',
 'ENSG00000166091_CMTM5',
 'ENSG00000026025_VIM',
 'ENSG00000205542_TMSB4X',
 'ENSG00000109099_PMP22',
 'ENSG00000145425_RPS3A',
 'ENSG00000172247_C1QTNF4',
 'ENSG00000072274_TFRC',
 'ENSG00000234745_HLA-B',
 'ENSG00000075340_ADD2',
 'ENSG00000119865_CNRIP1',
 'ENSG00000198938_MT-CO3',
 'ENSG00000135046_ANXA1',
 'ENSG00000235169_SMIM1',
 'ENSG00000101200_AVP',
 'ENSG00000167996_FTH1',
 'ENSG00000163565_IFI16',
 'ENSG00000117450_PRDX1',
 'ENSG00000124570_SERPINB6',
 'ENSG00000112077_RHAG',
 'ENSG00000051523_CYBA',
 'ENSG00000107130_NCS1',
 'ENSG00000055118_KCNH2',
 'ENSG00000029534_ANK1',
 'ENSG00000169567_HINT1',
 'ENSG00000142089_IFITM3',
 'ENSG00000139278_GLIPR1',
 'ENSG00000142227_EMP3',
 'ENSG00000076662_ICAM3',
 'ENSG00000143627_PKLR',
 'ENSG00000130755_GMFG',
 'ENSG00000160593_JAML',
 'ENSG00000095932_SMIM24',
 'ENSG00000197956_S100A6',
 'ENSG00000171476_HOPX',
 'ENSG00000116675_DNAJC6',
 'ENSG00000100448_CTSG',
 'ENSG00000100368_CSF2RB',
 'ENSG00000047648_ARHGAP6',
 'ENSG00000198918_RPL39',
 'ENSG00000196154_S100A4',
 'ENSG00000233968_AL157895.1',
 'ENSG00000137642_SORL1',
 'ENSG00000133816_MICAL2',
 'ENSG00000130208_APOC1',
 'ENSG00000105610_KLF1']
print('important columns ',len(important_cols))
important_cols_84 = important_cols

important columns  84

In [18]:
os.chdir('../..')

In [19]:
all_genes = np.loadtxt('2.preprocess_to_feature/cite/all_genes_names.txt', dtype=str)
all_genes

array(['ENSG00000121410_A1BG', 'ENSG00000268895_A1BG-AS1',
       'ENSG00000175899_A2M', ..., 'ENSG00000162378_ZYG11B',
       'ENSG00000159840_ZYX', 'ENSG00000074755_ZZEF1'], dtype='<U41')

In [20]:
use_imp_cols_84 = np.loadtxt('2.preprocess_to_feature/cite/use_imp_cols_84.txt')#, dtype=str)
use_imp_cols_84

array([ 3290.,  4010.,  4743.,  4841.,  5172.,  5260.,  5619.,  5632.,
        5939.,  6120.,  6699.,  6704.,  6705.,  6710.,  6713.,  6714.,
        6716.,  6720.,  6733.,  6734.,  6735.,  6737.,  6741.,  6744.,
        6749.,  6750.,  6756.,  6759.,  6761.,  6762.,  6763.,  6768.,
        6771.,  6774.,  6777.,  7292.,  7338.,  7616.,  7688.,  7772.,
        8238.,  8747.,  9331.,  9602.,  9908.,  9948., 10500., 10588.,
       10589., 10602., 10603., 10606., 10732., 10904., 10937., 10956.,
       11309., 11398., 11597., 11662., 13011., 13390., 13801., 14785.,
       15124., 15266., 15571., 16503., 17087., 17138., 17323., 17339.,
       17512., 17514., 17750., 17826., 18436., 18449., 18660., 18762.,
       19495., 19923., 20095., 20883.])

In [21]:
use_cols_84 = np.loadtxt('2.preprocess_to_feature/cite/use_cols_84.txt')#, dtype=str)
use_cols_84

array([0.0000e+00, 1.0000e+00, 2.0000e+00, ..., 2.2082e+04, 2.2083e+04,
       2.2084e+04])

In [22]:
private_test_input

AnnData object with n_obs Ã— n_vars = 26867 Ã— 22085
    obs: 'kaggle_dataset', 'day', 'donor', 'cell_type'

In [23]:
private_test_input.X

<26867x22085 sparse matrix of type '<class 'numpy.float32'>'
	with 127598600 stored elements in Compressed Sparse Row format>

In [24]:
# private_test_input = private_test_input[:, use_cols_84]
df_use = private_test_input_raw[:, use_cols_84]  # _raw
#print(df_use.X)

sc.pp.normalize_per_cell(df_use)
sc.pp.log1p(df_use.X)

with open('2.preprocess_to_feature/cite/svd_model_fitted_128.pkl', 'rb') as file:
    svd = pickle.load(file)
    
result_svd = svd.transform(df_use.X)

test_cite_pp = pd.DataFrame(result_svd, index = private_test_input_raw.obs_names)     # has cell_ids   # _raw

#test_cite_pp.to_pickle(feature_path + f'test_{svd_save_name}.pickle')

# important protein cols ---------------------------------------------------------------------

df_important = private_test_input_raw.X[:, use_imp_cols_84]   # _raw
df_important = sc.AnnData(X = df_important)
sc.pp.normalize_per_cell(df_important)
sc.pp.log1p(df_important)

test_imp = pd.DataFrame(df_important.X.toarray(), index = private_test_input_raw.obs_names).add_prefix('imp_')   # _raw

#test_imp.to_pickle(feature_path + f'test_{imp_save_name}.pickle')

/usr/local/lib/python3.8/dist-packages/scanpy/preprocessing/_simple.py:524: ImplicitModificationWarning: Trying to modify attribute `.obs` of view, initializing view as actual.
  adata.obs[key_n_counts] = counts_per_cell

In [25]:
test_cite_pp = test_cite_pp.add_prefix('base_svd_')
test_cite_pp.head()

,base_svd_0,base_svd_1,base_svd_2,base_svd_3,base_svd_4,base_svd_5,base_svd_6,base_svd_7,base_svd_8,base_svd_9,...,base_svd_118,base_svd_119,base_svd_120,base_svd_121,base_svd_122,base_svd_123,base_svd_124,base_svd_125,base_svd_126,base_svd_127
"CATAAGCAGCATGATA-1-('27678', 7)",81.000809,17.529505,22.640501,6.250456,-9.783189,-4.482016,-9.853884,2.868057,-1.303613,3.889945,...,-1.377417,-0.273728,-0.738601,-0.602925,-0.466023,-0.172758,-0.773262,-0.482636,0.626286,-0.387399
"GGTGATTGTATGAAAC-1-('27678', 7)",80.484848,2.830306,-8.349777,-0.183432,2.895543,-2.139858,0.033855,-3.715303,2.588200,1.178734,...,-0.741002,-0.129783,0.057323,-0.267614,0.250653,0.596740,1.089177,1.023226,-0.510319,0.012178
"ATAGGCTAGCTCTGTA-1-('27678', 7)",61.298729,28.147226,11.399919,-0.946990,5.687176,-1.222754,-2.267920,-8.198421,-5.788848,1.633933,...,-2.515137,1.853986,-0.046002,0.003497,0.562408,0.996404,-1.506272,1.654089,-0.255254,-1.557034
"TCATGAGGTGGATTTC-1-('27678', 7)",75.682724,21.903784,11.444319,14.161778,-11.635022,1.049297,-1.524715,-4.974929,-2.653662,4.637526,...,0.553922,-0.442595,-0.031483,-0.281389,1.000716,-0.432515,0.443957,-0.552058,-0.646036,0.535711
"TAAGCGTTCGGCTGGT-1-('27678', 7)",87.513260,3.752852,2.252877,-10.731239,-3.716068,6.564659,4.366943,-2.206863,1.639761,-2.452151,...,0.333302,-0.312694,0.385820,0.204652,-0.505665,-0.496095,-0.737861,0.657566,0.059061,0.261602

In [26]:
test_imp.head()

,imp_0,imp_1,imp_2,imp_3,imp_4,imp_5,imp_6,imp_7,imp_8,imp_9,...,imp_74,imp_75,imp_76,imp_77,imp_78,imp_79,imp_80,imp_81,imp_82,imp_83
"CATAAGCAGCATGATA-1-('27678', 7)",0.0,0.000000,0.0,3.908991,0.000000,1.139067,0.0,4.934837,2.452665,0.000000,...,1.139067,1.139067,0.0,0.000000,0.723641,0.000000,1.139067,5.109567,4.957489,4.376795
"GGTGATTGTATGAAAC-1-('27678', 7)",0.0,0.000000,0.0,1.847891,0.000000,0.000000,0.0,3.894221,1.663384,1.143767,...,1.143767,2.003600,0.0,2.003600,1.847891,1.847891,0.727203,3.432048,4.956851,3.432048
"ATAGGCTAGCTCTGTA-1-('27678', 7)",0.0,0.000000,0.0,3.306528,0.000000,0.000000,0.0,3.699704,0.000000,0.000000,...,1.683005,1.683005,0.0,0.000000,0.000000,0.000000,0.000000,4.200588,5.172006,3.802588
"TCATGAGGTGGATTTC-1-('27678', 7)",0.0,0.856593,0.0,3.427926,0.856593,0.000000,0.0,3.960711,1.622426,0.000000,...,0.000000,0.856593,0.0,0.000000,0.000000,0.000000,0.000000,5.828300,4.644288,4.250083
"TAAGCGTTCGGCTGGT-1-('27678', 7)",0.0,0.000000,0.0,2.234174,0.000000,0.000000,0.0,3.426908,2.354230,0.000000,...,0.000000,1.218616,0.0,1.218616,1.939642,0.000000,1.520335,4.827435,5.025780,0.784473

### preprocess input data - make-features

In [31]:
X_test_svd_128 = pd.concat([test_cite_pp.reset_index(drop=True), 
                            test_imp.reset_index(drop=True),
                           ], axis = 1)
X_test_svd_128   # final X_test

,base_svd_0,base_svd_1,base_svd_2,base_svd_3,base_svd_4,base_svd_5,base_svd_6,base_svd_7,base_svd_8,base_svd_9,...,imp_74,imp_75,imp_76,imp_77,imp_78,imp_79,imp_80,imp_81,imp_82,imp_83
0,81.000809,17.529505,22.640501,6.250456,-9.783189,-4.482016,-9.853884,2.868057,-1.303613,3.889945,...,1.139067,1.139067,0.000000,0.000000,0.723641,0.000000,1.139067,5.109567,4.957489,4.376795
1,80.484848,2.830306,-8.349777,-0.183432,2.895543,-2.139858,0.033855,-3.715303,2.588200,1.178734,...,1.143767,2.003600,0.000000,2.003600,1.847891,1.847891,0.727203,3.432048,4.956851,3.432048
2,61.298729,28.147226,11.399919,-0.946990,5.687176,-1.222754,-2.267920,-8.198421,-5.788848,1.633933,...,1.683005,1.683005,0.000000,0.000000,0.000000,0.000000,0.000000,4.200588,5.172006,3.802588
3,75.682724,21.903784,11.444319,14.161778,-11.635022,1.049297,-1.524715,-4.974929,-2.653662,4.637526,...,0.000000,0.856593,0.000000,0.000000,0.000000,0.000000,0.000000,5.828300,4.644288,4.250083
4,87.513260,3.752852,2.252877,-10.731239,-3.716068,6.564659,4.366943,-2.206863,1.639761,-2.452151,...,0.000000,1.218616,0.000000,1.218616,1.939642,0.000000,1.520335,4.827435,5.025780,0.784473
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26862,83.985542,0.151095,-7.608615,1.255235,-3.760198,0.768499,3.697361,-0.555503,0.845734,4.232537,...,0.000000,1.937320,0.000000,1.091938,1.091938,1.783409,0.688145,3.322536,4.653505,3.248456
26863,79.652626,5.136962,-11.205755,1.634926,0.798823,-1.257489,1.650426,-1.551127,0.893220,3.876749,...,0.000000,1.561850,0.000000,1.561850,0.000000,1.561850,1.256116,4.383529,4.850808,3.805677
26864,79.869690,9.435549,13.608870,15.537944,10.549198,-4.067131,20.577028,5.025831,0.764988,-0.663896,...,0.000000,1.279221,0.831569,0.000000,0.000000,0.000000,0.000000,6.235761,4.083643,0.000000
26865,83.211983,-2.192045,0.362601,3.691030,13.217938,7.373592,-3.658378,-4.596884,2.397793,0.866549,...,0.000000,0.000000,1.281697,0.000000,0.000000,0.000000,2.955912,1.956296,4.381402,0.624645
26866,86.613716,-8.767029,4.686262,2.732423,7.253230,10.462569,-7.014515,0.708084,3.988559,3.968848,...,0.000000,0.000000,0.921506,0.000000,0.000000,0.000000,2.780725,3.099327,4.299018,0.563344

In [32]:
with open('4.model/pred/private_X_test_svd_from_raw.pkl', 'wb') as f:   # _raw
    pickle.dump(X_test_svd_128, f)

### get sample per cell type for SHAP

In [27]:
sample = ad.AnnData(X=X_test_svd_128, obs=metadata_filtered)
sample

AnnData object with n_obs Ã— n_vars = 26867 Ã— 212
    obs: 'kaggle_dataset', 'day', 'donor', 'cell_type'

In [30]:
np.unique(sample.obs['cell_type'])

array(['BP', 'EryP', 'HSC', 'MasP', 'MkP', 'MoP', 'NeuP'], dtype=object)

In [31]:
sample[sample.obs.cell_type == 'BP']

View of AnnData object with n_obs Ã— n_vars = 99 Ã— 212
    obs: 'kaggle_dataset', 'day', 'donor', 'cell_type'

In [32]:
sampled_adata = sample[sample.obs.cell_type == 'BP'].obs.sample(n=5, random_state=42)
sample[sampled_adata.index].obs

                                kaggle_dataset  day  donor cell_type
CTCCCTCGTATGAAAC-1-('32606', 7)   test_private    7  32606        BP
CATGCAATCGAAATCC-1-('27678', 7)   test_private    7  27678        BP
AAGCGAGGTTCATCGA-1-('31800', 7)   test_private    7  31800        BP
TTCGCTGAGAAAGTCT-1-('27678', 7)   test_private    7  27678        BP
TCCAGAACATCTCATT-1-('31800', 7)   test_private    7  31800        BP

In [33]:
# get indices of 5 samples per cell type
unique_types = np.unique(sample.obs['cell_type'])

sample_obs = []

for t in unique_types:
    sampled_rows = sample[sample.obs.cell_type == t].obs.sample(n=5, random_state=42)
    sample_obs.append(sampled_rows.index)

In [34]:
sample_obs

[Index(['CTCCCTCGTATGAAAC-1-('32606', 7)', 'CATGCAATCGAAATCC-1-('27678', 7)',
        'AAGCGAGGTTCATCGA-1-('31800', 7)', 'TTCGCTGAGAAAGTCT-1-('27678', 7)',
        'TCCAGAACATCTCATT-1-('31800', 7)'],
       dtype='object'),
 Index(['GGAGATGTCTGAGAAA-1-('32606', 7)', 'CTTCCTTCACAAACGG-1-('27678', 7)',
        'ACTATGGTCATGGTAC-1-('27678', 7)', 'GTGCACGCAACCTATG-1-('13176', 7)',
        'CCTCACACACAAGTGG-1-('27678', 7)'],
       dtype='object'),
 Index(['CAATCGACACGGTGTC-1-('13176', 7)', 'GATCATGCAGTGACCC-1-('31800', 7)',
        'CTAAGTGCAACCCGCA-1-('27678', 7)', 'ATGACCACAAAGTATG-1-('31800', 7)',
        'AGCGCTGAGCTGCCAC-1-('32606', 7)'],
       dtype='object'),
 Index(['TATACCTCAAGCACCC-1-('31800', 7)', 'TGACGCGGTGCGACAA-1-('27678', 7)',
        'TAAGCACCAATCGCAT-1-('31800', 7)', 'CGAAGGATCTCAACCC-1-('31800', 7)',
        'TCGCTTGGTCGTTTCC-1-('31800', 7)'],
       dtype='object'),
 Index(['AGCGTATCAACAAGTA-1-('27678', 7)', 'TCATTTGTCAGACCTA-1-('32606', 7)',
        'TGCTTCGGTTGGACCC-1-('27678', 7)', 'TCCGGGAGTCTTGCTC-1-('31800', 7)',
        'GAAGGGTAGGTCCCGT-1-('13176', 7)'],
       dtype='object'),
 Index(['CGAAGTTCAGTCGGTC-1-('13176', 7)', 'TTGACCCAGCCTCGTG-1-('32606', 7)',
        'CATTCTAGTGATCGTT-1-('31800', 7)', 'CAGAGCCTCTACAGGT-1-('27678', 7)',
        'TCTATCAAGAAACTAC-1-('13176', 7)'],
       dtype='object'),
 Index(['GAGAAATGTAGTACGG-1-('27678', 7)', 'GTTTGGAGTGGGTTGA-1-('31800', 7)',
        'GTGGAAGTCAGCACCG-1-('32606', 7)', 'CTTCTCTCAGACAATA-1-('32606', 7)',
        'ACCCTCAAGCATTGAA-1-('31800', 7)'],
       dtype='object')]

In [35]:
# get rows in dataset corresponding to sampled indices
private_test_input_sample = sample[[elem for index_obj in sample_obs for elem in index_obj.tolist()]]

In [48]:
private_test_input_sample.obs

                                kaggle_dataset  day  donor cell_type
CTCCCTCGTATGAAAC-1-('32606', 7)   test_private    7  32606        BP
CATGCAATCGAAATCC-1-('27678', 7)   test_private    7  27678        BP
AAGCGAGGTTCATCGA-1-('31800', 7)   test_private    7  31800        BP
TTCGCTGAGAAAGTCT-1-('27678', 7)   test_private    7  27678        BP
TCCAGAACATCTCATT-1-('31800', 7)   test_private    7  31800        BP
GGAGATGTCTGAGAAA-1-('32606', 7)   test_private    7  32606      EryP
CTTCCTTCACAAACGG-1-('27678', 7)   test_private    7  27678      EryP
ACTATGGTCATGGTAC-1-('27678', 7)   test_private    7  27678      EryP
GTGCACGCAACCTATG-1-('13176', 7)   test_private    7  13176      EryP
CCTCACACACAAGTGG-1-('27678', 7)   test_private    7  27678      EryP
CAATCGACACGGTGTC-1-('13176', 7)   test_private    7  13176       HSC
GATCATGCAGTGACCC-1-('31800', 7)   test_private    7  31800       HSC
CTAAGTGCAACCCGCA-1-('27678', 7)   test_private    7  27678       HSC
ATGACCACAAAGTATG-1-('31800', 7)   test_private    7  31800       HSC
AGCGCTGAGCTGCCAC-1-('32606', 7)   test_private    7  32606       HSC
TATACCTCAAGCACCC-1-('31800', 7)   test_private    7  31800      MasP
TGACGCGGTGCGACAA-1-('27678', 7)   test_private    7  27678      MasP
TAAGCACCAATCGCAT-1-('31800', 7)   test_private    7  31800      MasP
CGAAGGATCTCAACCC-1-('31800', 7)   test_private    7  31800      MasP
TCGCTTGGTCGTTTCC-1-('31800', 7)   test_private    7  31800      MasP
AGCGTATCAACAAGTA-1-('27678', 7)   test_private    7  27678       MkP
TCATTTGTCAGACCTA-1-('32606', 7)   test_private    7  32606       MkP
TGCTTCGGTTGGACCC-1-('27678', 7)   test_private    7  27678       MkP
TCCGGGAGTCTTGCTC-1-('31800', 7)   test_private    7  31800       MkP
GAAGGGTAGGTCCCGT-1-('13176', 7)   test_private    7  13176       MkP
CGAAGTTCAGTCGGTC-1-('13176', 7)   test_private    7  13176       MoP
TTGACCCAGCCTCGTG-1-('32606', 7)   test_private    7  32606       MoP
CATTCTAGTGATCGTT-1-('31800', 7)   test_private    7  31800       MoP
CAGAGCCTCTACAGGT-1-('27678', 7)   test_private    7  27678       MoP
TCTATCAAGAAACTAC-1-('13176', 7)   test_private    7  13176       MoP
GAGAAATGTAGTACGG-1-('27678', 7)   test_private    7  27678      NeuP
GTTTGGAGTGGGTTGA-1-('31800', 7)   test_private    7  31800      NeuP
GTGGAAGTCAGCACCG-1-('32606', 7)   test_private    7  32606      NeuP
CTTCTCTCAGACAATA-1-('32606', 7)   test_private    7  32606      NeuP
ACCCTCAAGCATTGAA-1-('31800', 7)   test_private    7  31800      NeuP

In [40]:
private_test_input_sample.write("private_test_input_sample.h5ad")